image: Visual Studio 2022

stack: node 17
branches:
  only:
    - main

install:
  - npm install

build: off
build_script:
  - npm run build

test_script:
  - npm run lint # && npm test

deploy_script: 
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "%USERPROFILE%\.git-credentials"
  - dir "%USERPROFILE%"  # Проверка содержимого директории
  - type "%USERPROFILE%\.git-credentials"  # Проверка содержимого файла
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose